import { auth } from '@/auth'
import { spotifyFetch } from '@/lib/spotify'
import { prisma } from '@/lib/prisma'

export async function POST(request: Request) {
  const session = await auth()
  if (!session) return Response.json({ error: 'Unauthorized' }, { status: 401 })

  const { trackUris, year } = await request.json()
  if (!Array.isArray(trackUris) || trackUris.length === 0) {
    return Response.json({ error: 'trackUris required' }, { status: 400 })
  }

  const playlistName = `Wavelength: ${year} Time Machine`

  // Create playlist
  const playlist = await spotifyFetch<{ id: string; external_urls: { spotify: string } }>(
    `/users/${session.user.id}/playlists`,
    session.accessToken,
    {
      method: 'POST',
      body: JSON.stringify({
        name: playlistName,
        description: `Generated by Wavelength — sounds of ${year}`,
        public: false,
      }),
    }
  )

  // Add tracks
  await spotifyFetch(
    `/playlists/${playlist.id}/tracks`,
    session.accessToken,
    {
      method: 'POST',
      body: JSON.stringify({ uris: trackUris }),
    }
  )

  // Persist to DB (best-effort)
  try {
    await prisma.user.upsert({
      where: { id: session.user.id },
      create: {
        id: session.user.id,
        spotifyId: session.user.id,
        displayName: session.user.name ?? 'Unknown',
        email: session.user.email,
      },
      update: {},
    })
    await prisma.savedPlaylist.create({
      data: {
        userId: session.user.id,
        spotifyId: playlist.id,
        name: playlistName,
        feature: 'timemachine',
      },
    })
  } catch {
    // non-fatal
  }

  return Response.json({ playlistUrl: playlist.external_urls.spotify })
}
